language: node_js
node_js:
  - "7.7.1"

before_script:
  - npm install -g typescript

after_success:
  - npm run test:coverage

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on: 
    branch: master
